command: ["python", "app.py"]

env:
  - name: SLACK_BOT_TOKEN
    value: "xoxb-xxxxxxxxxxxxx-xxxxxxxxxxxxxxx-xxxxxxxxxxxxx"
  - name: SLACK_SIGNING_SECRET
    value: "xxxxxxxxxxxxxxxxxxxxxx"
  - name: SLACK_APP_TOKEN
    value: "xapp-1-xxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxx"
  - name: DATABRICKS_GENIE_SPACE_ID
    value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  - name: PORT
    value: "3000"
  - name: LOG_LEVEL
    value: "INFO"
